astra_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('qa_app.urls')),
    path('', include('data_sets.urls')),
    # path('', include('core.urls'))
]

core/urls.py
from django.urls import include, path
from . views import index, qa_index, submit_question
app_name = 'core'
urlpatterns = [
    path('', qa_index, name='qa_index'),
    path('submit/   ', submit_question, name='submit_question')
]

qa_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, submit_question
# app_name = "cnn_daily"
urlpatterns = [
    path('', index, name="index"),
    path('submit/', submit_question, name="submit_question"),

]

core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from pgvector.django import VectorField

class LangchainPgCollection(models.Model):
    name = models.CharField(blank=True, null=True)
    cmetadata = models.TextField(blank=True, null=True)  # This field type is a guess.
    uuid = models.UUIDField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'langchain_pg_collection'


class LangchainPgEmbedding(models.Model):
    collection = models.ForeignKey(LangchainPgCollection, models.DO_NOTHING, blank=True, null=True)
    embedding = VectorField(dimensions=1536)  # This field type is a guess.
    document = models.CharField(blank=True, null=True)
    cmetadata = models.TextField(blank=True, null=True)  # This field type is a guess.
    custom_id = models.CharField(blank=True, null=True)
    uuid = models.UUIDField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'langchain_pg_embedding'

core/views.py
from django.shortcuts import render
from core.models import LangchainPgEmbedding
from core.embed import embed_input
from pgvector.django import L2Distance
import uuid
from django.views.decorators.http import require_POST


def index(request):

  if request.method == "POST":
    text = request.POST.get('input_text')
    embedding = embed_input(text)
    embeding_model = LangchainPgEmbedding.objects.create(
      uuid=uuid.uuid4(),
      embedding=embedding,
      document=text,
    )
    print(embeding_model.pk)
    document = LangchainPgEmbedding.objects.order_by(
      L2Distance('embedding', embedding)
      ).first()
    context = {
      'text' : text,
      'similar_search_result' : document,
    }
    return render(request=request, template_name='core/results.html', context=context)
  embeddings = LangchainPgEmbedding.objects.all()
  context = {'embeddings' : embeddings}
  return render(request=request, template_name='core/index.html', context=context)



def qa_index(request):
    articles = LangchainPgEmbedding.objects.all()
    context = {'articles' : articles}
    return render(request=request, template_name="core/qa_index.html", context=context)


@require_POST
def submit_question(request):
    prompt = request.POST.get("prompt")
    instruction = request.POST.get("qa-instructions")
    # answer = run_retrieval_qa_pipeline(prompt, instruction)
    # Answers.objects.create(row_id=uuid4(), question=prompt, answer=answer)
    context = { 'question' :  prompt, 'answer' : 'answer'}
    return render(request=request, template_name="core/qa_response.html", context=context)

templates/core/index.html
{% include "base.html" %}

{% block content %}
<div class="container">
<h1>Index Core</h1>

<div class='mb-4'>
  <form method="POST">
    {% csrf_token %}
    <div class='form-group'>
      <label for="input-text">Enter Text</label>
      <textarea name="input_text" id="input-text" class="form-control mb-2" cols="10" rows="10"></textarea>
    </div>
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
  </form>
</div>
{% for embedding in embeddings %}
{{embedding.document}}
<pre>{{embedding.embedding}}</pre>

{% endfor %}

</div>
{% endblock content %}

templates/core/qa_index.html
{% include "base.html" %}

{% block content %}
<div class="row">
<div class="col-8">
    <ul class="list-group">
{% for article in articles %} 
<li class="list-group-item">
<h1 class="text-success">{{ article.collection.name }}Article #{{ forloop.counter }}</h1>
 <p class="fw-light">{{ article.document }}</p>
 
</li>
{% endfor %}
</ul>
</div>

<div class="col-4 ml-4">
    <form method="POST" action="{% url 'core:submit_question' %}">
        {% csrf_token %}

        <div class="mb-3">
            <label for="qa-prompt" class="form-label">*Enter your query:</label>
            <textarea id="qa-prompt" name="prompt" class="form-control" rows="4" required></textarea>
        </div>

		<div class="mb-3">
            <label for="qa-instructions" class="form-label">
                Enter any instructions for customizing your answer.</br>
                <em>For example: "Answer in Italian"</em>
            </label>
            <textarea id="qa-instructions" name="qa-instructions" class="form-control" rows="2"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>
</div> 



{% endblock content %}

templates/core/qa_response.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <p class="p-4 bg-secondary">{{ question }}</p>

        <p class="p-4 fst-italic">{{ answer }}</p>
    

        <a href="{% url 'core:qa_index' %}">Back to articles</a>
    </div>
</div>

{% endblock %}

templates/core/results.html
{% include "base.html" %}

{% block content %}


<h1>Result</h1>
<h3>Original Text</h3>
 <p>{{ text }}</p>
<h3>Most similar document</h3>

<p>{{ similar_search_result.document }}</p>

<a href={% url 'core:index' %}>Back to List</a>


{% endblock content %}