astra_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('qa_app.urls')),
    path('', include('data_sets.urls')),
    # path('', include('core.urls'))
]

core/urls.py
from django.urls import include, path
from . views import index, qa_index, submit_question
app_name = 'core'
urlpatterns = [
    path('', qa_index, name='qa_index'),
    path('submit/   ', submit_question, name='submit_question')
]

data_sets/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, show_collection, create_collection, search_collection, interact_collection 
app_name = "data_set"
urlpatterns = [
    path('', index, name="index"),
    path('create-collection/', create_collection, name="create_collection"),
    
    path('show-collection/<str:uuid>/', show_collection, name="show_collection"),
    path('search-collection/<str:uuid>/', search_collection, name="search_collection"),
    path('interact-collection/<str:uuid>/', interact_collection, name="interact_collection"),

] 

data_sets/models.py
from django.db import models

class DataSet(models.Model):
    name = models.CharField(max_length=250)
    def __str__(self):
        return f"{self.name}"
    

class Data(models.Model):
    data_set = models.ForeignKey(DataSet, on_delete=models.CASCADE)
    description = models.CharField(max_length=250)
    content = models.TextField()
    def __str__(self):
        return f"{self.data_set.name} : {self.description}"
    
from django.db import models
from pgvector.django import VectorField

class UserDataCollection(models.Model):
    name = models.CharField(blank=True, null=True)
    cmetadata = models.TextField(blank=True, null=True)  # This field type is a guess.
    uuid = models.UUIDField(primary_key=True)

    # class Meta:
    #     managed = True
    #     db_table = 'data_collection'
    # def __str__(self):
    #     return self.name
    

class UserDataEmbedding(models.Model):
    collection = models.ForeignKey(UserDataCollection, on_delete=models.CASCADE, blank=True, null=True, related_name="embeddings")
    embedding = VectorField(dimensions=1536)  # This field type is a guess.
    document = models.CharField(blank=True, null=True)
    cmetadata = models.TextField(blank=True, null=True)  # This field type is a guess.
    custom_id = models.CharField(blank=True, null=True)
    uuid = models.UUIDField(primary_key=True)

    # class Meta:
    #     managed = True
    #     db_table = 'data_embedding'
    
    

data_sets/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from .models import UserDataEmbedding, UserDataCollection
from .embedder import embed_input
import uuid
from pgvector.django import L2Distance


def index(request):
    context = {}
    return render(request=request, template_name='data_sets/index.html', context=context)




def create_collection(request):
    if request.method == "POST":
        name = request.POST.get('collection_name') 
        print(name)

        create_collection = UserDataCollection.objects.create(
          uuid=uuid.uuid4(),
          name=name,
        )
        
        

        print(create_collection.name)
        context = {}
        
        return redirect('data_set:show_collection', uuid=create_collection.uuid)
    context = {}
    return render(request=request, template_name='data_sets/create_collection.html', context=context)

# @require_POST
# def create_data_embedding(request, uuid):
#     data_collection = DataCollection.objects.get(uuid=uuid)
#     text = request.POST.get('create_data_embedding')
#     embedding = embed_input(text)
#     print(text)
#     data_embedding = DataEmbedding.objects.create(
#         collection=uuid,
#         embedding=embedding,
#         document=text,
#         )
#     context = {"data_collection" : data_collection}
    
#     return redirect(request.path)
    

def show_collection(request, uuid):
    data_collection = UserDataCollection.objects.get(uuid=uuid)
    if request.method == "POST":
        text = request.POST.get('create_data_embedding')
        embedding = embed_input(text)
        # print(text)

        import uuid
        data_embedding = UserDataEmbedding.objects.create(
            uuid=uuid.uuid4(),
            collection=data_collection,
            embedding=embedding,
            document=text,
        
        )

        context = {"data_collection" : data_collection}
        return render(request=request, template_name='data_sets/show_collection.html', context=context)
    return render(request=request, template_name='data_sets/show_collection.html', context=context)
 

def search_collection(request, uuid):
    data_collection = UserDataCollection.objects.get(uuid=uuid)
    if request.method == "POST":
        search = request.POST.get('search_embeddings')
        embedding = embed_input(search)
        document = UserDataEmbedding.objects.order_by(
        L2Distance('embedding', embedding)
        ).first()
        context = {
        'search' : search,
        'similar_search_result' : document,
        }

        
        return render(request=request, template_name='data_sets/search_collection.html', context=context)
    context = {"data_collection" : data_collection}
    return render(request=request, template_name='data_sets/search_collection.html', context=context)
 

def interact_collection(request, uuid):
    data_collection = UserDataCollection.objects.get(uuid=uuid)
    if request.method == "POST":
        search = request.POST.get('search_embeddings')
        embedding = embed_input(search)
        document = UserDataEmbedding.objects.order_by(
        L2Distance('embedding', embedding)
        ).first()
        documents = UserDataCollection.objects.get(collection=data_collection.uuid)
        print(documents)
        context = {
        'search' : search,
        'similar_search_result' : document,
        'documents' : documents
        }

        
        return render(request=request, template_name='data_sets/interact_collection.html', context=context)
    context = {"data_collection" : data_collection}
    return render(request=request, template_name='data_sets/interact_collection.html', context=context)
 

templates/data_sets/create_collection.html
{% include "base.html" %}
<div class="container">
{% block content %}

<article>
    <header>Header</header>
    <form method="POST" action="{% url 'data_set:create_collection' %}">
        {% csrf_token %}
    
    
    
      
          <!-- Markup example 1: input is inside label -->
          <label for="dataset_name">
            Data Set
            <input type="text" id="collection_name" name="collection_name" placeholder="Data set name" required>
          </label>
    
      
    
        <!-- Button -->
        <button type="submit">Submit</button>
      
      </form>
    
    <footer>Footer</footer>
  </article>

{% endblock content %}
</div>

templates/data_sets/index.html
{% include "base.html" %}
<div class="container">
{% block content %}

<h1>Index DataSet</h1>



{% endblock content %}
</div>

templates/data_sets/interact_collection.html
{% include "base.html" %}
<div class="container">
{% block content %}

<div class="grid">
  <div>
    {% for data in data_collection.embeddings.all  %}
    {{data.document}}
    <p>------</p>
    <br>
    {% endfor %}
  </div>


  <div> <form method="POST" action="">      
    {% csrf_token %}

    
        <label for="create_data_embedding" class="form-label">*Search embedding:</label>
        <input id="search_embeddings" name="search_embeddings" class="form-control"/>
    



    <button type="submit" class="btn btn-primary">Submit</button>

</form>
</div>
</div>
{{data_collection.name}}
   

<h1>Result</h1>
<h3>Original Text</h3>
 <p>{{ search }}</p>
<h3>Most similar document</h3>

<p>{{ similar_search_result.document }}</p>
</div> 
{% endblock content %}

templates/data_sets/search_collection.html
{% include "base.html" %}
<div class="container">
{% block content %}
{{data_collection.name}}
    <form method="POST" action="">     
        {% csrf_token %}

        
            <label for="create_data_embedding" class="form-label">*Search embedding:</label>
            <input id="search_embeddings" name="search_embeddings" class="form-control"/>
        



        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
 

<h1>Result</h1>
<h3>Original Text</h3>
 <p>{{ search }}</p>
<h3>Most similar document</h3>

<p>{{ similar_search_result.document }}</p>
</div> 
{% endblock content %}

templates/data_sets/show_collection.html
{% include "base.html" %}
<div class="container">
{% block content %}
{{data_collection.name}}
    <form method="POST" action="">     
        {% csrf_token %}

        
            <label for="create_data_embedding" class="form-label">*create_data_embedding:</label>
            <input id="create_data_embedding" name="create_data_embedding" class="form-control"/>
        



        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
 
</div> 

{% endblock content %}